Added exit if any scp fails

diff --git a/portable_env b/portable_env
--- a/portable_env
+++ b/portable_env
@@ -54,6 +54,9 @@ ss ()
   for x in ~/.portable_env/*
    do
     scp "$x" "$connect":~/".""$session""$(basename "$x")" 2>&1 >/dev/null && echo -n "."
+    if [[ $? != 0 ]]; then echo "Could not connect" &&  exit 1
+    fi
+
   done
   echo
 
